// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Nameservers
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("nameserverCount")]
        public long? NameserverCount { get; set; }

        [JsonProperty("hasMultipleProviders")]
        public bool? HasMultipleProviders { get; set; }

        [JsonProperty("nameservers")]
        public Nameserver[] Nameservers { get; set; }

        [JsonProperty("uniqueOwners")]
        public string[] UniqueOwners { get; set; }
    }

    public partial class Nameserver
    {
        [JsonProperty("nameserver")]
        public string NameserverNameserver { get; set; }

        [JsonProperty("ipAddresses")]
        public string[] IpAddresses { get; set; }

        [JsonProperty("reverseDns")]
        public string ReverseDns { get; set; }

        [JsonProperty("owner")]
        public string Owner { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
